apiVersion: apps/v1
kind: Deployment
metadata:
  name: mall-auth-deployment
  namespace: default
  labels:
    app: mall-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall-auth
  template:
    metadata:
      labels:
        app: mall-auth
    spec:
      #使用sidecar方式挂载skywalking-agent
      initContainers:
        - name: init-skywalking-agent
          image: 172.16.33.163/mall/skywalking-agent:8.9.0
          command:
            - 'sh'
            - '-c'
            - 'set -ex;mkdir -p /vmskywalking/agent;cp -r /skywalking/* /vmskywalking/agent;chmod -R 775 /vmskywalking/agent;'
          volumeMounts:
            #挂在目录/vmskywalking/agent到log-volume卷
            - mountPath: /vmskywalking/agent
              name: log-volume
      containers:
        - name: mall-auth
          # 指定Docker Hub中的镜像地址
          image: 172.16.33.163/mall/mall-auth:1.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8401
          env:
            # 指定环境
            - name: spring.profiles.active
              value: prod
            # 指定时区
            - name: TZ
              value: Asia/Shanghai
            # 指定Nacos地址
            - name: spring.cloud.nacos.discovery.server-addr
              value: http://172.16.33.162:8848
            - name: spring.cloud.nacos.config.server-addr
              value: http://172.16.33.162:8848
          volumeMounts:
            - mountPath: /var/logs
              name: log-volume
      volumes:
        - name: log-volume
          hostPath:
            path: /mydata/app/mall-auth/logs
            type: DirectoryOrCreate