apiVersion: v1
kind: Service
metadata:
  name: mall-portal-service
  namespace: default
spec:
  # 为了外部能访问SpringBootAdmin监控，将类型改为NodePort
  type: NodePort
  selector:
    app: mall-portal
  ports:
    - name: http
      protocol: TCP
      port: 8085
      targetPort: 8085
      #暴露node端口
      nodePort: 30203